### ISSUE TITLE
Does not support netstandard2.0

### ISSUE THREAD

**Issue by yosbeleg89** [artiomchi/FlexLabs.Upsert#1]
Trying to install on a netstandard2.0 project:

`Package FlexLabs.EntityFrameworkCore.Upsert 1.0.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package FlexLabs.EntityFrameworkCore.Upsert 1.0.1 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)`

Maybe you can target netstandard2.0 instead of netcoreapp2.0?

Thanks

**Comment by artiomchi** [comment]
Huh, you're absolutely right! How did I miss that?

I'll fix it straight away!

**Comment by artiomchi** [comment]
Fixed in version 1.0.2 and deployed to NuGet!
