### ISSUE TITLE
Excluding columns when updating

### ISSUE THREAD

**Issue by vludax** [artiomchi/FlexLabs.Upsert#10]
Hi, thanks for creating the library!

We'd like to use to upsert rows based on secondary IDs. If the secondary ID is matched, we want to update all columns except the PK. We tried this:
```c#
ctx.Upsert(newItem)
	.On(i => new { i.SecondaryID1, i.SecondaryID2 })
	.UpdateColumns(existingItem => new Item
	{
		ID = existingItem.ID, // We want to preserve the original ID
		Field1 = default(string),
		Field2 = default(string)
	})
```
Unfortunately this throws `System.Reflection.TargetException: 'Object does not match target type.'` in `ExpressionHelper.cs:25`

Could you please advise if we're doing it wrong or this is not supported? Thanks!

**Comment by artiomchi** [comment]
I'm assuming the first key is the primary key? Then you shouldn't even be specifying it in the `UpdateColumns` method. This method should only have columns that need new values. So if a column's value doesn't change (esp if it's a PK) you shouldn't use it there.

Let me know if that sorts out the problem :)

**Comment by vludax** [comment]
Thanks for the prompt response!
Not specifying the value for the PK was causing an SQL error saying ID can't be null. We fixed that by adding a default value of `NEWID()` (we're using SQL Server). Works like a charm. Thanks again!
