### ISSUE TITLE
Exception due to null constant in expression + Fix.

### ISSUE THREAD

**Issue by timaiv** [artiomchi/FlexLabs.Upsert#130]
**Version**
6.0.1
**Exception message:**
`The parameterized query '(@p0 bigint,@p1 datetime2(7),@p2 int,@p3 int,@p4 varchar(100),@p' expects the parameter '@p5', which was not supplied.`
**How to reproduce:**
```cs
.WhenMatched((dbTx, upTx) => new TransactionInfo()
                    {
                        SenderId = dbTx.SenderId == null ? upTx.SenderId : dbTx.SenderId
                    })
```
**Fix:**
In `PrepareDbCommandArgument` change `dbParameter.Value = constantValue.Value` to `dbParameter.Value = constantValue.Value ?? DBNull.Value`
Microsoft does same in ` CreateParameter` (`parameter.Value = value ?? DBNull.Value;`)

**Comment by andznui** [comment]
I'm seeing the same issue. Looks like there is a proposed fix in the comment already. is there an ETA for the fix to get in @artiomchi ?
@timaiv is there a workaround meanwhile?

**Comment by andznui** [comment]
actually, for the example in the issue a simple workaround is to use the coalesce operator. 
```
.WhenMatched((dbTx, upTx) => new TransactionInfo()
                    {
                        SenderId = dbTx.SenderId ?? upTx.SenderId
                    })
```

Works for my use-case too.

**Comment by hertznsk** [comment]
Fix !160 works correctly for us. Is it possible to consider including it in the next version? @artiomchi

**Comment by artiomchi** [comment]
This has now been patched and deployed in the latest built! Thank you for the reports, and apologies for the delay
