### ISSUE TITLE
Is there a way to overwrite all properties when matched?

### ISSUE THREAD

**Issue by isaevdan** [artiomchi/FlexLabs.Upsert#132]
Is there a way to update all properties when matched? Basically I want to provide constant with all new values and generate update which will update everything. 
The goal is to have value in database updated/inserted to state of provided variable

```
_dbContext.Set<TEntity>().Upsert(entity)
            .On(v => v.Id)
            .WhenMatched((_) => entity)
            .WithFallbackExpressionCompiler()
            .RunAsync(cancellationToken);
```

**Comment by artiomchi** [comment]
Hi @isaevdan,

Yes, if you just skip the `.WhenMatched()` call, the default behaviour is to update all writeable properties to the values in the entity you provided
