### ISSUE TITLE
Upsert verion 7.0.0 - Error:Method not found - Net Core 8 Preview 7

### ISSUE THREAD

**Issue by BartNSTCL** [artiomchi/FlexLabs.Upsert#150]
I can't find anything on the Internet but when I updated code to use Net Core 8 Preview 7 (dotnet-sdk-8.0.100-preview.7.23376.3-win-x64), the code fails at the Upsert command. The error is:

Error:Method not found: 'System.Collections.Generic.IEnumerable`1 Microsoft.EntityFrameworkCore.Metadata.IEntityType.GetProperties()'. at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.PrepareCommand[TEntity](IEntityType entityType, ICollection`1 entities, Expression`1 match, Expression`1 updater, Expression`1 updateCondition, RunnerQueryOptions queryOptions)+MoveNext() at FlexLabs.EntityFrameworkCore.Upsert.Runners.RelationalUpsertCommandRunner.RunAsync[TEntity](DbContext dbContext, IEntityType entityType, ICollection`1 entities, Expression`1 matchExpression, Expression`1 updateExpression, Expression`1 updateCondition, RunnerQueryOptions queryOptions, CancellationToken cancellationToken) in /_/src/FlexLabs.EntityFrameworkCore.Upsert/Runners/RelationalUpsertCommandRunner.cs:line 398

I was unable to find the 7.0.0 source code but I suspect Preview 7 removed this function.

**Comment by xoko14** [comment]
Which version of EntityFrameworkCore are you using? FlexLabs.Upsert only supports up to EntityFrameworkCore 7.

**Comment by BartNSTCL** [comment]
It was working with EntityFrameworkCore 8 until Preview 7. I can wait until EntityFrameworkCore 8 is released, which I believe is around November.

**Comment by Nizio-Dev** [comment]
Can confirm, it doesn't work on latest preview release of EF8.

**Comment by znematov** [comment]
Hey thanks for the the library!, any plans to support for .NET 8?

I am using .NET 8 & EF8 with 8.0.0-rc.2.23480.1 version and getting the same exception.

**Comment by artiomchi** [comment]
.NET 8 support has just been deployed in the latest version! Sorry for the delay
