### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by vypsim** [artiomchi/FlexLabs.Upsert#153]
First of all, let me start by saying this is a great library which provides an elegant solution to a common requirement.

I came in to submit an issue I'm having but noticed there is already an issue open for it and many other open issues with no response that I can see from the maintainer(s).

Is this library still being actively maintained and would you be open to taking on new maintainers?

**Comment by artiomchi** [comment]
Hi @vypsim - I have found myself with most limited time to maintain the library as of late, but I'm trying to get to it at least once a year with new .NET releases, as well as if there are any major issues identified.

Any contributions are absolutely welcome, and I will try to respond to them in a more timely manner in the future.

I have realised that I have notifications set up for PRs, but not for issues though, which was an unfortunate oversight :(

**Comment by vypsim** [comment]
Thanks @artiomchi, I appreciat the response and will attempt to raise a PR for the issue I'm having soon.
