### ISSUE TITLE
MySQL provider package renamed to MySql.EntityFrameworkCore

### ISSUE THREAD

**Issue by naomai** [artiomchi/FlexLabs.Upsert#167]
Hello @artiomchi, thanks for creating this great addition to EF Core. It helps me transitioning my legacy code into a more elegant solution.

I ran into problem when using it with current MySQL provider. My call to Upsert function ends up with `database provider not supported yet` exception.

This might be due to deprecating the name of `MySql.Data.EntityFrameworkCore` package, and dropping `Data` from the name. It is mentioned in [nuget page of the old package](https://www.nuget.org/packages/MySql.Data.EntityFrameworkCore).
A quick peek into MySQL runner reveals this check, with only the legacy provider listed:

https://github.com/artiomchi/FlexLabs.Upsert/blob/09e5dc51d784e064133a6975c972471027cec8cd/src/FlexLabs.EntityFrameworkCore.Upsert/Runners/MySqlUpsertCommandRunner.cs#L16

Would it be possible to support the new package?

**Comment by artiomchi** [comment]
Ahh, I didn't know about that change.
Of course, happy to make a change to support the new name! This will be out in the new release later today!
