### ISSUE TITLE
"On" nested object as comparison value

### ISSUE THREAD

**Issue by Nizio-Dev** [artiomchi/FlexLabs.Upsert#169]
Hello. Is there a possibility to use nested object as a matching?

In example: I have Object car and the car has property Engine. Is it possible to do .On(car => car.Engine.Model) ?

When I tried to do this, i got this error at run time: "Match columns have to be properties of the TEntity class".

**Comment by artiomchi** [comment]
This is not supported in the library. I didn't have the time to support features like "OwnedEntities", where this might be possible - but if in your case the Engine object is in a different table, then you wouldn't be able to do that at all in SQL in the first place.
