### ISSUE TITLE
support for MySQL / MariaDB

### ISSUE THREAD

**Issue by collinbarrett** [artiomchi/FlexLabs.Upsert#2]
Cool project! Do you know how difficult it would be to add support for MySQL/MariaDB 's `INSERT ON DUPLICATE KEY UPDATE`? My guess is that it wouldn't be too different from PostgreSQL. I [rolled my own](https://github.com/collinbarrett/FilterLists/blob/master/src/FilterLists.Data/Seed/Extensions/SeedFilterListsDbContext.cs) in one of my projects, but not sure how flexible/secure/performant it really is.

**Comment by artiomchi** [comment]
Quite easy to do, actually. I've already written a prototype in the develop branch yesterday, but I wanted to test it first before I put it live.

**Comment by collinbarrett** [comment]
very cool, thanks! I'll try to find some time to test it out as well. it might take me a couple weeks, though.

**Comment by artiomchi** [comment]
I've just pushed a new build to NuGet, v1.0.3

One of the main features is MySQL support. I've tested it, and it seems to work. I also added some unit tests that run against an actual MySql database to make sure I keep an eye on it :)
