### ISSUE TITLE
Add support for constructor expressions in WhenMatched

### ISSUE THREAD

**Issue by dmitriifilonenko** [artiomchi/FlexLabs.Upsert#24]
Currently it's implicitely allowed to create objects in WhenMatched method by using only MemberInitExpression which causes an exception in such case:
```
dataContext.Users.UpsertRange(users)
          .On(u => u.Id)
          .WhenMatched((uInDb, uNew) =>
                    new User(uInDb.Id, uNew.Username, uNew.FirstName, uNew.LastName, uInDb.Created));
```
The exception comes from this code in RelationalUpsertCommandRunner.PrepareCommand method:
```
                if (!(updater.Body is MemberInitExpression entityUpdater))
                    throw new ArgumentException("updater must be an Initialiser of the TEntity type", nameof(updater));
```
I'm not sure but maybe it will be enough just to add a check if updater.Body is NewExpression:

```
                if (!(updater.Body is MemberInitExpression) && !(updater.Body is NewExpression))
                    throw new ArgumentException("updater must be an Initialiser of the TEntity type");
```
I would prefer to have initialization of an object in a constructor in order to keep its properties as readonly, without setters. Now in order to make Upsert work I have to expose properties' setters in entities which makes their contract too broad.

**Comment by artiomchi** [comment]
Hi @dmitriifilonenko 

This is a complex one.

The library is reading the expression tree passed to `.WhenMatched` to find out which properties are updated, and what values are being set. If you want to use a constructor there, there's no way to identify what query we should be generating (with the way the library works right now, at least).

The only alternative I can think of is adding a new override to `WhenMatched`, which will receive a dictionary (or an anonymous object) allowing you to set values to arbitrary properties. But the downside of that is that you'd lose any kind of compile time checking of property names, and if you rename/remove a property in the future - you wouldn't get an exception - the values would just not be updated.

If that's an acceptable solution for your situation, I can look into implementing it, but it doesn't sound like a good idea :)

**Comment by dmitriifilonenko** [comment]
Hi @artiomchi 

Thanks for your reply!
Ok, I think I understand what you mean. 

I was thinking about this the following way: if it's a NewExpression then code must assume that it should take **all** properties of the object in expression and update with them **all** columns in a correspondent row. So you can probably still work with properties (no dictionaries, no anonymous objects). It's just that these properties get their values not in setters but in constructor. Does it make sense for you? Sorry, I'm not a big expert in expressions. :)

My use case is following: on a restart of a service I want to sync its data with data from another service (like user data in the example from my feature request) because it could have changed while my service was down. And I don't want to check if user's Firstname or Lastname were changed. This will make me to write long if..else in WhenMatched. It's easier just to update entire row for a user with an existing ID.

**Comment by artiomchi** [comment]
Hi Dmitrii,

The `WhenMatched` expression is only used to update properties of an entity, and isn't used during the insert. I just use the `NewExpression` there because it's the easiest way to describe which **subset of** properties have to be updated, and which values should they get. It doesn't imply that we're using these values when we're creating a new instance of the entity.

In your scenario, if I understood this right, you don't care for specifying which properties should be updated since you want ALL of them to be updated, is that right?

In this case, you can skip the `WhenMatched` call completely.

If you call the following, the library will insert a new instance of the user if it isn't already in the DB, and if it exists, it will update all the properties to the new values in the passed object

```c#
dataContext.Users.UpsertRange(users)
    .On(u => u.Id)
    .RunAsync();
```

**Comment by artiomchi** [comment]
Hey @dmitriifilonenko, did you manage to get the library to work in your project?

**Comment by dmitriifilonenko** [comment]
Hi @artiomchi ,

Yes, thank you! Well, basically I use it with properties setters though it's a bit against my pursuit of minimal contracts. :-)
In my case I update not all the properties, the rest are 'updated' by existing values in DB.
So now it looks like this:
```
await dataContext.Users.Upsert(user)
                    .On(u => u.PhysicalUserId)
                    .WhenMatched((uInDb, uNew) =>
                        new User
                        {
                            PhysicalUserId = uInDb.PhysicalUserId,
                            Username = uNew.Username,
                            FirstName = uNew.FirstName,
                            LastName = uNew.LastName,
                            PictureLink = uNew.PictureLink,
                            Rank = uInDb.Rank,
                            Stars = uInDb.Stars,
                            Created = uInDb.Created
                        })
                    .RunAsync();
```
Generally it works. So I left it 'as is' for now. Maybe later when I have some time (he-he!) I will try to play with it a bit more. 
But if you have on mind any better tip for usage I will be happy to try it!

**Comment by artiomchi** [comment]
One small tip I'd suggest is that you don't have to update columns with existing values if you don't want them to change.. Also, you'd not be able to change the join key anyway, so that can be excluded too. So you could slightly simplify this to:

```csharp
await dataContext.Users.Upsert(user)
    .On(u => u.PhysicalUserId)
    .WhenMatched((uInDb, uNew) =>
        new User
        {
            Username = uNew.Username,
            FirstName = uNew.FirstName,
            LastName = uNew.LastName,
            PictureLink = uNew.PictureLink,
        })
    .RunAsync();
```

I'm glad it's working for you, even if it's not perfect yet. If you have any ideas on how I can improve it (and when you get some time :wink:) you could always open up another issue, or maybe even write a PR, if you want!

**Comment by dmitriifilonenko** [comment]
Thanks for for the tip @artiomchi! And for the quick feedback.

**Comment by contactsureshh** [comment]
Hi @artiomchi, @jmosbech, I was looking for same use case (Constructor expressions) support. Not sure if either of you got a chance to fix this use case? :)

Additionally I was just wondering if we can also add support for below use case?

`DataContext.Countries.Upsert(newCountry)
    .On(c => c.ISO)
    .UpdateIf(e => e.Status == null)
    .WhenMatched(cDb => cDb.UpdateSomething(false))
    .RunAsync();`

_where UpdateSomething() is just updating value of some property of that object._

Thanks.
