### ISSUE TITLE
Navication Properties Throw Exceptions

### ISSUE THREAD

**Issue by CraigSelbert** [artiomchi/FlexLabs.Upsert#26]
I was not sure how best to describe the issue so I forked the code, created a new branch to exercise the code the same way I was in my project that was throwing the exception. 

Take a look at the file NavigationPropertyTests.cs in my branch 
https://github.com/CraigSelbert/FlexLabs.Upsert/tree/bug/NavigationProperty
for an example of the issue. If I have time I will see if I can fix but I figured I would at lease show you what I am experiencing.

**Comment by artiomchi** [comment]
Hi @CraigSelbert,

This is what you're trying to do:
```c#
await myRepository.UpsertAsync(new Event 
{
    Name = "Name", 
    User = new User
    {
        Id = 1,
        Name = "User One"
    }
});
```

Unfortunately, this is not currently supported. What you're doing is trying to upsert two entities of different types, including creating a foreign key between them. That just wouldn't translate to a single command.

You'll have to upsert the `User` object first, get it's ID, then upsert the `Event` referencing the user you upserted.

We might look into expanding the library to support something like this in the future, but it will require a massive restructuring, and a pretty large change of the scope of the project, so I can't promise that this will happen any time soon

**Comment by CraigSelbert** [comment]
@artiomchi ,

Thanks for the response. I understand what you are saying. I updated my code to first save the user then use the associated property but it still fails with the same object null reference error on RelationalUpsertCommandRunner Line 132. 

```
var user = await _myContext.Users.AddAsync(@event.User);

@event.User = user.Entity;

await _myContext.Events
        .Upsert(@event)
        .On(x => x.Id)
        .WhenMatched(x => new Event { Position = @event.Position })
        .RunAsync();

await _myContext.SaveChangesAsync();
```

It this is not going to work that if fine, I just really like the option of the upsert for SQL Server.

**Comment by artiomchi** [comment]
Now.. A different issue I see here is that your `Events` you're using your `Id` column as the `On` column. You shouldn't do that, because it's an auto increment column, so the `On` will never match, and the `Upsert` will always insert a new entry to the db.

You should use it on a non identity unique column/column set on your table. Depending on what `Event` represents, there are different options that could be used, but I'm guessing the sample you provided isn't a real example :)

**Comment by artiomchi** [comment]
Hey @CraigSelbert, did you manage to get the library to work in your project?

**Comment by artiomchi** [comment]
I'm closing this issue, since there weren't an update on it for a couple months. Let me know if you have any more issues
