### ISSUE TITLE
'match must be an anonymous object initialiser'

### ISSUE THREAD

**Issue by Hamidnwo** [artiomchi/FlexLabs.Upsert#3]
Hi, thanks for this helpful library.
I'm encountering a problem when using a string field as the "On" parameter. 
How can I fix this please.

Here's the code I'm writing:

public class Settings
{
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
}

db.Upsert(new Settings { Name = "BaseUrl", Type = "String", Value = "1", Comment = "1" })
                .On(c => c.Name).RunAsync();

**Comment by artiomchi** [comment]
Oh, whoops! I completely overlooked this!

It was a feature that was supposed to work from the start, but I forgot to finish it! My apologies :(

I just patched the repo, and pushed a new build to NuGet. It should be available to download from there shortly

**Comment by Hamidnwo** [comment]
Thanks man, I really appreciate it :D
