### ISSUE TITLE
Syntax error with Postgres when omitting `WhenMatched(...)`

### ISSUE THREAD

**Issue by floyd-may** [artiomchi/FlexLabs.Upsert#32]
I'm getting a syntax error from postgres when doing an upsert. The SQL it generates is of the form

```sql
INSERT INTO "TableName" AS "T" ("ColumnA", "ColumnB") VALUES (@p0, @p1) ON CONFLICT ("ColumnA", "ColumnB") DO UPDATE SET
```

It seems that there's an assumption that the `WhenMatched(...)` expression will get translated to SQL and inserted following the `SET`, but I'm using the library like this:

```csharp
DataContext.TableNames
    .Upsert(new TableName
    {
        ColumnA = val1,
        ColumnB = val2
    })
    .On(v => new { v.UserID, v.Date })
    .RunAsync();
```

based on some code-surfing, it seems that the design of the `UpsertCommandBuilder<T>` makes assumptions that calls to `.On(...)` will be followed by calls to `.WhenMatched(...)`. This isn't obvious to the programmer, and won't blow up until runtime. In my case, my automated tests against the in-memory store also worked as expected, so it passed my CI build.

In my humble opinion, a short-term solution might be to default `_noUpdate` to `true` and set it to `false` when `.WhenMatched(...)` is called. This all depends on the intention of the design. In any case, though, **it should be impossible (i.e. a compiler error) to call `.Run()` or `.RunAsync()` if the generated SQL would be invalid.**

I'd also be glad to help you work through the fluent API design details in the longer term if you'd like.
It just so happens I wrote [a Pluralsight course](https://www.pluralsight.com/courses/designing-fluent-apis-c-sharp) about this very topic - there are some concepts there that might be helpful.

**Comment by artiomchi** [comment]
Hey @floyd-may 

That's definitely a but, although your analysis is a bit off. The commend builder actually allows you to run `.Run()` or `.RunAsync()` straight away on purpose - since in a lot of configurations it's a valid scenario.

In this case, you're running Upsert on a table that doesn't have any columns to update, so the query is building the last part of the query incorrectly.

It's a very simple patch, luckily, and a new build (v2.0.3) is already being pushed to NuGet!

**Comment by floyd-may** [comment]
So far 2.0.3 is behaving better.

**Comment by artiomchi** [comment]
Thanks for confirming that 2.0.3 has fixed the issue

> Also, can you elaborate on this? I'm not sure I understood it.

I think I understand what you meant by suggesting the improvements to the fluent API I built, but it's actually working as intended. If you take a look at the [Usage](https://github.com/artiomchi/FlexLabs.Upsert/wiki/Usage) page, you can see the following paragraph:

> Both the On and the WhenMatched calls can be omitted. If the On call is not made, the matching will be done on the primary key on the table. If the WhenMatched call is omitted, the upsert command will update all the remaining calls on the table, which are not marked as primary keys or are auto generated.

**Comment by floyd-may** [comment]
As long as the programmer isn't responsible for understanding what sequences of calls do and don't produce valid SQL then I'd agree - working as intended. Thanks for your hard work on this project!
