### ISSUE TITLE
Exception when passing an empty collection to UpsertRange(...)

### ISSUE THREAD

**Issue by floyd-may** [artiomchi/FlexLabs.Upsert#33]
When an empty collection is passed to `.UpsertRange(...)`, an `InvalidOperationException` is thrown. The `.First()` call here is at the top of the stack trace:

https://github.com/artiomchi/FlexLabs.Upsert/blob/2.0.3/src/FlexLabs.EntityFrameworkCore.Upsert/Runners/PostgreSqlUpsertCommandRunner.cs#L28

**Comment by artiomchi** [comment]
Sorry for the long turnaround on this one. I've been away a bit :)

I just fixed it and deployed v2.0.4 with the fix
