### ISSUE TITLE
SqlServerUpsertCommandRunner (and possibly others) do not support null column matchers

### ISSUE THREAD

**Issue by APIWT** [artiomchi/FlexLabs.Upsert#42]
When using SQL Server, if you have a column that allows null as a value in the On matcher, the search condition produced in the query does not properly check null and causes the query to fail. This is because when you are checking for null in most relational databases you should use `IS NULL` or `IS NOT NULL` rather than the equality operator.

The following pull request should fix this issue: https://github.com/artiomchi/FlexLabs.Upsert/pull/41

**Comment by artiomchi** [comment]
Great work Anthony, thanks for your help on this!

I've added some enhancements to your code, by only applying your patch for nullable columns, and keeping a simple match for non nullable ones.

I'm just pushing a new build (v2.0.6) to NuGet, which should be indexed and available to download within the next hour!

Let me know if it works as expected! I'll keep the issue open until then

**Comment by APIWT** [comment]
This seems to work great! I really appreciate your quick action.

By the way, inside `TestDbContext` I think you have a slight error.

Where you have:
```csharp
modelBuilder.Entity<NullableCompositeKey>().HasIndex(t => new { t.ID1, t.ID2 }).IsUnique();
```

I believe it should be:
```csharp
modelBuilder.Entity<NullableCompositeKey>().HasIndex(t => new { t.ID1, t.ID2 }).IsUnique().HasFilter(null);
```

There is some justification here: https://docs.microsoft.com/en-us/ef/core/modeling/relational/indexes

Thanks again for everything.

**Comment by artiomchi** [comment]
Oh yeah, you're absolutely right!

Sorry it took me so long to reply. I'll patch that straight away
