### ISSUE TITLE
Support for IQueryable<TEntity> as data source for UpsertRange<TEntity>?

### ISSUE THREAD

**Issue by vzwick** [artiomchi/FlexLabs.Upsert#43]
I am faced with a scenario where it would be super desireable to be able to pass an `IQueryable<TEntity>` to `UpsertRange<TEntity>` instead of an `IEnumerable<TEntity>` or `TEntity[]`. 

This should then result in the UPSERT being run entirely on the DB side as opposed to loading entities into memory. I.e.:

```
var someSourceEntitiesProjectionToDailyVisits = dataContext.SomeSourceEntities
    .Where(x => x.SomeSourceEntityProperty == someValue)
    .Select(x => new {
        UserID = x.SomeFieldMatchedToUserId,
        Date = DateTime.UtcNow.Date
    });

dataContext.DailyVisits
    .UpsertRange(someSourceEntitiesProjectionToDailyVisits)
    .On(v => new { v.UserID, v.Date })
    .WhenMatched(v => new DailyVisit
    {
        Visits = v.Visits + 1,
    })
    .RunAsync();
```

Is something like this on the roadmap?

**Comment by vzwick** [comment]
Side note: Since EF doesn't allow projections to Entity types, `UpsertRange` and the `UpsertCommandBuilder` would also have to be extended to accept anonymous types, I guess?

So, basically:

```
public static UpsertCommandBuilder<TEntity, TProjection> UpsertRange<TEntity, TProjection>(this DbSet<TEntity> dbSet, IQueryable<TProjection> entities)
            where TEntity : class
{
   // ...
}
```

**Comment by APIWT** [comment]
Can you give an example query that you would expect as a result of this operation? I am not sure how this would even work.

**Comment by vzwick** [comment]
@APIWT let's assume, for the sake of the example, that I have a `SuperSpecialDailyVisits` table in my DB, containing `Id`, `UserId`, `Date` and `MagicSauce` properties. 

Now, if I wanted to upsert my `SuperSpecialDailyVisits` where `MagicSauce` is `"CocktailSauce"` into `DailyVisits`, incrementing the existing item's `Visits` property by 1 for every `SuperSpecialDailyVisit` matched on `UserId` and `VisitDate`, I would need to do this:

```
var visitsToUpsert = dataContext
    .SuperSpecialDailyVisits
    .Where(x => x.SecretSauce == "CocktailSauce")
    .ToList() // This is a bad idea when we're talking about a couple million rows in the table!
    .Select(x => new DailyVisit() {
        UserID = x.UserId,
        Date = x.Date
    }); // This Select() is necessary because UpsertRange() expects an IEnumerable<DailyVisit>

dataContext.DailyVisits
    .UpsertRange(visitsToUpsert)
    .On(v => new { v.UserID, v.Date })
    .WhenMatched(v => new DailyVisit
    {
        Visits = v.Visits + 1,
    })
    .RunAsync();
```

My proposed version would be:

```
var visitsToUpsert = dataContext
    .SuperSpecialDailyVisits
    .Where(x => x.SecretSauce == "CocktailSauce"); // No ToList(), no pointless materialization - should be translated into SQL and performed DB-side

dataContext.DailyVisits
    .UpsertRange(visitsToUpsert) // Needs to accept non-T IQueryables in order for this to work! Also, the IQueryable needs to be translated to SQL rather than materializing it to an IEnumerable. 
    .On(v => new { v.UserID, v.Date })
    .WhenMatched(v => new DailyVisit
    {
        Visits = v.Visits + 1,
    })
    .RunAsync();
```

I hope that sheds some light on the use case.

**Comment by vzwick** [comment]
The SQL version hopefully illustrates this a bit better ..:

```
MERGE DailyVisits
	with (holdlock) AS [target] 
USING (
	SELECT * from SuperSpecialDailyVisits
	where SecretSauce = 'CocktailSauce'
) AS [source]
ON ([target].[UserID] = [source].[UserID] and [target].[Date] = [source].[Date])
WHEN MATCHED BY TARGET
    UPDATE target SET [Visits] = [Visits] + 1
-- etc
```

**Comment by APIWT** [comment]
Okay, this totally makes sense to me now. It is similar to the INSERT INTO ... SELECT ... ON DUPLICATE KEY UPDATE pattern that I grew to love in MySQL. I am not sure what it will take to implement something like this so I'll let @artiomchi take it from here. Sorry I could not be more helpful :(

**Comment by vzwick** [comment]
@artiomchi - what's your take on this?

**Comment by artiomchi** [comment]
I've been thinking about it for some time, and I don't think it's something that the Upsert library should handle.

The main purpose of the library is to add something that wasn't easy to do with pure T-Sql, like running an upsert command on entities outside the database.

If you're trying to take a IQueryable, and run an upsert on that, then you're better off just running the SQL command, or wrapping it in a Stored Procedure


Even if I tried to implement it, it would end up being a lot more complex, as I'd have to get the SQL generated by the IQueryable, and figure out how to merge that into a upsert command, which is outside the current scope of the project.

**Comment by artiomchi** [comment]
Going to close this issue due to inactivity. Also, as explained above - this is too much outside the scope of this project
