### ISSUE TITLE
Proposed feature add: .UpdateAllColumns()

### ISSUE THREAD

**Issue by floyd-may** [artiomchi/FlexLabs.Upsert#46]
I propose the addition of the following:

```csharp
            await context.Set<Thing>()
                .Upsert(thing)
                .On(x => x.SomeColumn)
                .UpdateAllColumns()
                .RunAsync();
```

It is unfortunate, especially for wide tables, to need to go and update the contents of `.WhenMatched(...)` whenever the column layout changes.

**Comment by artiomchi** [comment]
Hi Floyd,

The library can already handle this out of the box.

As listed in the [Usage](https://github.com/artiomchi/FlexLabs.Upsert/wiki/Usage) wiki page: 
> If the WhenMatched call is omitted, the upsert command will update all the remaining calls on the table, which are not marked as primary keys or are auto generated.
