### ISSUE TITLE
Transactional support

### ISSUE THREAD

**Issue by APIWT** [artiomchi/FlexLabs.Upsert#54]
Hey @artiomchi!

I have a question. What is your recommendation in using one or more upserts in a transaction?
https://docs.microsoft.com/en-us/ef/core/saving/transactions

We have a couple instances of mixing typical Add/Update calls with Upsert and we want it to rollback if any of them fail.

I do understand that it might not be possible to modify this library to use `SaveChangesAsync` rather than `RunAsync`, but is there a workaround you can suggest?

Hope you are having a great day!

**Comment by artiomchi** [comment]
Si basically you can create your own transaction scope, and all upserts will run within this transaction, since they're all triggered from the data context.

I haven't considered this scenario, but that's pretty cool. Thanks for pointing this out @BigApple1988
