### ISSUE TITLE
Postgres - UpdateIf() with DateTime throws exception

### ISSUE THREAD

**Issue by Shamshiel** [artiomchi/FlexLabs.Upsert#56]
Today I tried the new method `UpdateIf()` with a DateTime but it doesn't seem to work.

```
await _context.MyEntity.Upsert(myEntity)
               .On(x => new { x.Id })
               .UpdateIf(x => x.Date >= date)
               .RunAsync();
```

I get the following error:

> "ERROR"
> "operator does not exist: timestamp without time zone >= integer"
> "No operator matches the given name and argument types. You might need to add explicit type casts."

Is it currently not possible to use DateTimes in the `UpdateIf()` method?

**Comment by Rohansi** [comment]
Seems to happen with SQL Server too.

**Comment by hsinyu-chen** [comment]
`.UpdateIf((x,y) => x.Date != y.Date )`
generate sql 
`WHEN MATCHED AND [T].[ChangeTime] != @p0`
and get @p0 not exists exception
should generate sql like following?
`  WHEN MATCHED AND [T].[ChangeTime] != [S].[ChangeTime] `

**Comment by artiomchi** [comment]
This is indeed a bug that was finally fixed this weekend.. (Thanks @grante for your PR!)

Should be deployed on NuGet soon
