### ISSUE TITLE
MySQL database set duplicity by other than PrimaryKey

### ISSUE THREAD

**Issue by PayteR** [artiomchi/FlexLabs.Upsert#61]
Hi, does `on()` method works on MySQL database? Because it looks, it always search only for Primary Key. Here is my example:
```
await _dbContext.Test.Upsert(entity)
                        .On(e => e.Column7)
                        .RunAsync();  
```
So i want to Update when Column7 match, but it generates query that newer match that column and then always insert new row.

```
INSERT INTO `app_test` 
(`column1`, `column2`, `column3`, `column4`, `column5`, `column6`, `column7`, `created_at`, `updated_at`) 
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8) 
ON DUPLICATE KEY UPDATE
 `column1` = VALUES(`column1`),
  `column2` = VALUES(`column2`), 
  `column3` = VALUES(`column3`), 
  `column4` = VALUES(`column4`), 
  `column5` = VALUES(`column5`), 
  `column6` = VALUES(`column6`), 
  `created_at` = VALUES(`created_at`),
  `updated_at` = VALUES(`updated_at`);
```

**Comment by APIWT** [comment]
As far as I know, `On` does not work with MySQL. This is because MySQL does not allow you to specify which constraints you want to respect in your query. You must create a unique or primary key on the `app_test` table with the columns that you want to match against.

**Comment by artiomchi** [comment]
That's right, there's no way to specify the `On` columns in MySql syntax. MySql uses the unique constraint present on the table to find matches, and if none are present - the primary key

That's just a limitation of the database engine

**Comment by PayteR** [comment]
Ok, so the only way to achieve this in MySQL is to add a unique key to this columns. Thx.

I think its worth to note that for example here https://github.com/artiomchi/FlexLabs.Upsert/wiki/MySql-Conditional-Updates.
