### ISSUE TITLE
UnsupportedExpressionException: OrElse

### ISSUE THREAD

**Issue by jmosbech** [artiomchi/FlexLabs.Upsert#65]
Hello,

Thank you for the library!

I'm trying to implement a conditional update to avoid overwriting the `CreatedOn` timestamp on a row unless something has changed. (Note: Ideally I would use `WhenMatched` to preserve the original value, but due to #24 I turned to `UpdateIf` instead).

I have the following piece of code:

```
var entity = new Department(
        dept.Name,
        dept.HospitalName,
        dept.Id)
    { CreatedOn = DateTime.UtcNow });

await _dbContext.Upsert(entity)
    .On(m => m.RemoteId)
    .UpdateIf((cDb, cIns) => cDb.Name != cIns.Name || cDb.HospitalName != cIns.HospitalName)
    .RunAsync();
```

Which throws the following exception: 

```
UnsupportedExpressionException: This type of expression is not currently supported: ((cDb.Name != cIns.Name) OrElse (cDb.HospitalName != cIns.HospitalName)). Simplify the expression, or try a different one.
```

Would it be possible to add support for this use-case? Or is there a better way (that doesn't involve parameterless constructors🙂)?

**Comment by artiomchi** [comment]
Hi Jonas,

That is a pretty simple expression to add support to. I've just added a commit with it, and if all goes well - it should go live within the next couple days

**Comment by artiomchi** [comment]
The new build is now live in NuGet: version 2.2.0

**Comment by jmosbech** [comment]
Very nice!!! Thanks a million. 👏👏
