### ISSUE TITLE
A complete working example

### ISSUE THREAD

**Issue by azuretrainer1** [artiomchi/FlexLabs.Upsert#68]
I am trying to use FlexLabs.Upsert package in my EF Core project.  I followed the example as per the documentation but when I use DataContext I am not able to find the Upsert method. Even the Visual Studio is not showing in the IntelliSense. 

Can you please provide a complete working example?

I am not able to figure out how to use this library based on your usage page.

```csharp
using FlexLabs.EntityFrameworkCore.Upsert;
//I am querying a different datasoure, converting datatable to a list of entities
List lstContractEntityList = dataTable.DataTableToList();
 public static string InsertSQLData(List<ContractEntity> lstContractEntityList)
        {
            try
            {
                
                using (var context = new BulkInsertUpdateContext())
                {
                                context .lstContractEntityList.------> Upsert is not showing up.
                }
            }
            catch (Exception ex)
            {
                return "0 RECORDS UPDATED" + ex.Message + ex.InnerException;
            }
            return "Updated Records with out exception";
        }


public class BulkInsertUpdateContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"server=*************;");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
    //entities
    public DbSet<ContractEntity> Contract { get; set; }
}
 ```

**Comment by jjxtra** [comment]
`using FlexLabs.EntityFrameworkCore.Upsert;`

**Comment by artiomchi** [comment]
Hi @azuretrainer1,

The `.Upsert()` call has to be done on the `DbSet<>` directly. If you convert it to a list, you'll load all entities from the database into memory, and upsert can not be called on the database from that.

Looking at your example, you'll need to do something like this (you can further customise the code with other options, using `.WhenMatched()` etc.  
See the Usage page for more examples: https://github.com/artiomchi/FlexLabs.Upsert/wiki/Usage

```csharp
using FlexLabs.EntityFrameworkCore.Upsert;

//I am querying a different datasoure, converting datatable to a list of entities
//List lstContractEntityList = dataTable.DataTableToList();

public static string InsertSQLData(List<ContractEntity> lstContractEntityList)
{
    try
    {
        using (var context = new BulkInsertUpdateContext())
        {
            context.Contract.Upsert(lstContractEntityList)
                .On(l => l.UniqueColumnInTable)
                .Run();
        }
    }
    catch (Exception ex)
    {
        return "0 RECORDS UPDATED" + ex.Message + ex.InnerException;
    }
    return "Updated Records with out exception";
}


public class BulkInsertUpdateContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"server=*************;");
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
    }
    //entities
    public DbSet<ContractEntity> Contract { get; set; }
}
```

Let me know if that works for you

**Comment by azuretrainer1** [comment]
@artiomchi,

Thank you so much for your help. I was able to get it working with the example you gave. Thank you for all the help. 

Also, the IntelliSense started showing the Upsert or UpsertRange methods after I installed Microsoft.EntityFrameworkCore.Tools package only. Please correct me if I am wrong. 

I have the following packages in my solutions
1. FlexLabs.EntityFrameworkCore.Upsert (2.2.1)
2. Microsoft.EntityFrameworkCore (2.2.6)
3. Microsoft.EntityFrameworkCore.SqlServer (2.2.6)
4. Microsoft.EntityFrameworkCore.Tools (2.2.6)

You may close the Issue. I am good to go for now.

**Comment by formalist** [comment]
Hi @artiomchi,
to make it work I needed also to add:

`using Microsoft.EntityFrameworkCore;`

It would be useful to update the wiki 'Usage' page with a full complete example. Thank you.
