### ISSUE TITLE
Error upsert on byte[] key

### ISSUE THREAD

**Issue by jjxtra** [artiomchi/FlexLabs.Upsert#69]
I get this error when I use a primary key that is a byte[] in the 'On' expression:

```
FlexLabs.EntityFrameworkCore.Upsert.InvalidMatchColumnsException : Using autogenerated / 
identity keys as the upsert match excession is not supported. Pick a non generated unique key. See 
https://go.flexlabs.org/upsert.identitykeymatch for more details
```
```
UpsertCommandBuilder<IPAddressInfo> builder = IPAddresses.Upsert(ip) // IPAddressInfo object
.On(i => i.IPAddress) // byte[]
.WhenMatched(v => new IPAddressInfo
{

});
```

**Comment by jjxtra** [comment]
Looks like line 79 is not doing correct logic for byte[]:

https://github.com/artiomchi/FlexLabs.Upsert/blob/0bf51c7f3b3cf4732036b09009689e339a9b1441/src/FlexLabs.EntityFrameworkCore.Upsert/Runners/UpsertCommandRunnerBase.cs

**Comment by artiomchi** [comment]
Actually, line 79 has nothing to do with the logic for `byte[]`. This is just the line that threw the exception - which in this case is because your unique key seems to be configured to be auto-generated in the DB. You can see more details in the link in the exception message.

Since your key is a byte array, that seems somewhat unlikely though. I assume the `IPAddress` property is not auto generated, but manually inserted? And it's the PK on that table? If that's the case, you might want to decorate it with this attribute:

```csharp
[DatabaseGenerated(DatabaseGeneratedOption.None)]
```

If that's not the case, could you show me your `IPAddressInfo` class?

**Comment by jjxtra** [comment]
Here is the class. Just trying to do an upsert where I insert a new ip address with count 1, or update the count of existing ip. In the debug window I can see the upsert sql statement generated and it looks correct, it's just that if I then try to fetch the ip address info after an expected upsert where the count should have been incremented, it is not incremented.

```
public class IPAddressInfo
{
    public byte[] IPAddress { get; set; }
    public int Count { get; set; }
}

// ...

// upsert code, works for first insert, but then for updates, count is not incremented
IPAddressInfo ip = new IPAddressInfo
{
    IPAddress = ipAddressBytes,
    Count = 1
};
await IPAddresses.Upsert(ip).On(i => i.IPAddress).WhenMatched(i =>
new IPAddressInfo
{
    Count = i.Count+ 1
}).RunAsync();

// now fetch ip by ipAddressBytes, count is never incremented

```

**Comment by jjxtra** [comment]
Debugging further into your code, it looks like parameters with value of 1 are being passed, just not consumed in sqlite engine properly, maybe due to matching on a blob?

**Comment by jjxtra** [comment]
This resolves the issue, apparently change tracking does not recognize the changes done by the upsert.
```
            ChangeTracker.AutoDetectChangesEnabled = false;
            ChangeTracker.LazyLoadingEnabled = false;
            ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
```
