### ISSUE TITLE
Overriding SaveChanges()

### ISSUE THREAD

**Issue by VictorioBerra** [artiomchi/FlexLabs.Upsert#7]
I add timestamps and modified by on SaveChanges() override. Is this possible?

**Comment by artiomchi** [comment]
Sorry, could you explain what you mean?

By the way, this plugin doesn't use `SaveChanges()` and instead builds a SQL statement and runs it immediately.

**Comment by VictorioBerra** [comment]
A lot of people do this https://benjii.me/2014/03/track-created-and-modified-fields-automatically-with-entity-framework-code-first/

I'm assuming due to the nature of this library, that will not work?

**Comment by artiomchi** [comment]
Ah, I see.

That's correct, Entity Framework can't do atomic upserts since it's change tracker expects the entity to first be loaded into memory, before running the update as a separate request. So the example you showed above won't have an impact on this library.
