### ISSUE TITLE
UpsertRange inserting duplicates in MySql

### ISSUE THREAD

**Issue by AirEssY** [artiomchi/FlexLabs.Upsert#72]
Hey all,
I'm having an issue with UpsertRange inserting duplicates and I can't work out why, possibly a bug?

I have the following trying to insert a list of 1000 POCO entity classes
```csharp
IEnumerable<Entry> entries = transformedEntryModels.Select(Map);

await _entriesContext.UpsertRange(entry)
   .On(entity => new { entity.ExternalId, entity.ProviderType })
   .RunAsync();
```

I run the same batch (with the same ExternalId & ProviderType), and I get duplicate rows for all of them... I would hope that it would try and run an update against all of those rows (and effectively do nothing since the data is identical)

The POCO entity class is crazy simple, and we're using EF Core & MySql
The ID is the primary key (By convention) as per the MS doco --> https://docs.microsoft.com/en-us/ef/core/modeling/keys

```csharp
public class Entry
    {
        public long ID { get; set; }
        public string AgentCode { get; set; }
        public string ExternalAgentId { get; set; }
        public ProviderType ProviderType { get; set; }
        public DateTimeOffset DateTimeUtc { get; set; }
        public int? Rating { get; set; }
        public string ExternalId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Neighbourhood { get; set; }
        public string Name { get; set; }
        public string OriginalSource { get; set; }
        public DateTimeOffset? Date { get; set; }
        public string S3Key { get; set; }
    }
```
We have no additional constraints set on DbContext via fluent api or anything like that...

If it helps (to see the versions/dependencies) here is the .csporoj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningsAsErrors></WarningsAsErrors>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.3.104.34" />
    <PackageReference Include="AsyncEnumerator" Version="3.1.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.104.36" />
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.0" />
    <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>

</Project>
```

Thanks for your help, I'm currently looking for alternative solutions :\

**Comment by artiomchi** [comment]
Hey @AirEssY 

Does your initial collection have any duplicates? If yes, your code has to figure out how to handle them. Different database engines can handle this differently, some might just run with it, some will throw exceptions.

If your input data has duplicates, you have to make sure to de-duplucate them, even if it'll be something as simple as this:

```csharp
IEnumerable<Entry> entries = transformedEntryModels.Select(Map)
    .GroupBy(entity => new { entity.ExternalId, entity.ProviderType })
    .Select(group => group.First());
```

**Comment by artiomchi** [comment]
Note, that this kind of de-duplication will lead to data loss (since you're ignoring second copies of matching rows).

If that's not what you want, instead of selecting the first entry from each group, you'll have to figure out what you want to return, which really depends on your business logic and your objects, hence can't be done automatically :)

**Comment by AirEssY** [comment]
I just had a look and there were no duplicates (Still an awesome pointer and I've added that code into my solution)

Running the UpsertRange (twice on an empty table), with the same batch of 1000 will end up with 2000 rows in the database... with every row getting duplicated.

**Comment by AirEssY** [comment]
I've logged the sql command from EF and it looks like this

> info: Microsoft.EntityFrameworkCore.Database.Command[20101]
>       Executed DbCommand (386ms) [Parameters=[@p0='?' (Size = -1), @p1='?' (Size = -1), @p2='?' (DbType = DateTime), @p3='?' (Size = -1), @p4='?' (Size = -1), @p5='?' (Size = -1), @p6='?' (Size = -1), @p7='?' (Size = -1), @p8='?' (DbType = Int32), @p9='?' (DbType = DateTime), @p10='?' (Size = -1), @p11='?' (DbType = Int32), @p12='?' (Size = -1), @p13='?' (Size = -1), @p14='?' (Size = -1), @p15='?' (Size = -1), @p16='?' (Size = -1), @p17='?' (Size = -1), @p18='?' (Size = -1), @p19='?' (DbType = DateTime), @p20='?' (Size = -1), @p21='?' (Size = -1), @p22='?' (Size = -1), @p23='?' (Size = -1), @p24='?' (Size = -1), @p25='?' (DbType = Int32), @p26='?' (DbType = DateTime), @p27='?' (Size = -1), @p28='?' (DbType = Int32), @p29='?' (Size = -1), @p30='?' (Size = -1), @p31='?' (Size = -1), @p32='?' (Size = -1), @p33='?' (Size = -1), @p34='?' (Size = -1), @p35='?' (Size = -1), @p36='?' (DbType = DateTime), @p37='?' (Size = -1), @p38='?' (Size = -1), @p39='?' (Size = -1), @p40='?' (Size = -1), @p41='?' (Size = -1), @p42='?' (DbType = Int32), @p43='?' (DbType = DateTime), @p44='?' (Size = -1), @p45='?' (DbType = Int32), @p46='?' (Size = -1), @p47='?' (Size = -1), @p48='?' (Size = -1), @p49='?' (Size = -1), @p50='?' (Size = -1), @p51='?' (Size = -1), @p52='?' (Size = -1), @p53='?' (DbType = DateTime), @p54='?' (Size = -1), @p55='?' (Size = -1), @p56='?' (Size = -1), @p57='?' (Size = -1), @p58='?' (Size = -1), @p59='?' (DbType = Int32), @p60='?' (DbType = DateTime), @p61='?' (Size = -1), @p62='?' (DbType = Int32), @p63='?' (Size = -1), @p64='?' (Size = -1), @p65='?' (Size = -1), @p66='?' (Size = -1), @p67='?' (Size = -1), @p68='?' (Size = -1), @p69='?' (Size = -1), @p70='?' (DbType = DateTime), @p71='?' (Size = -1), @p72='?' (Size = -1), @p73='?' (Size = -1), @p74='?' (Size = -1), @p75='?' (Size = -1), @p76='?' (DbType = Int32), @p77='?' (DbType = DateTime), @p78='?' (Size = -1), @p79='?' (DbType = Int32), @p80='?' (Size = -1), @p81='?' (Size = -1), @p82='?' (Size = -1), @p83='?' (Size = -1), @p84='?' (Size = -1)], CommandType='Text', CommandTimeout='300']
>       INSERT INTO `Entry` (`AgentCode`, `City`, `DateTimeUtc`, `ExternalAgentId`, `ExternalId`, `Location`, `Neighbourhood`, `PostalCode`, `Rating`, `Date`, `OriginalSource`, `ProviderType`, `Text`, `Title`, `Name`, `S3Key`, `State`) VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16), (@p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33), (@p34, @p35, @p36, @p37, @p38, @p39, @p40, @p41, @p42, @p43, @p44, @p45, @p46, @p47, @p48, @p49, @p50), (@p51, @p52, @p53, @p54, @p55, @p56, @p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67), (@p68, @p69, @p70, @p71, @p72, @p73, @p74, @p75, @p76, @p77, @p78, @p79, @p80, @p81, @p82, @p83, @p84) ON DUPLICATE KEY UPDATE `AgentCode` = VALUES(`AgentCode`), `City` = VALUES(`City`), `DateTimeUtc` = VALUES(`DateTimeUtc`), `ExternalAgentId` = VALUES(`ExternalAgentId`), `Location` = VALUES(`Location`), `Neighbourhood` = VALUES(`Neighbourhood`), `PostalCode` = VALUES(`PostalCode`), `Rating` = VALUES(`Rating`), `Date` = VALUES(`Date`), `OriginalSource` = VALUES(`OriginalSource`), `Text` = VALUES(`Text`), `Title` = VALUES(`Title`), `Name` = VALUES(`Name`), `S3Key` = VALUES(`S3Key`), `State` = VALUES(`State`)

(Yes sorry gross and hard to read)...
The part that caught my eye was `ON DUPLICATE KEY UPDATE`... because the data is not duplicate by KEY (since ID is the key and that is an auto-incremented bigint), they are duplicated by the columns I provided in the On command (ExternalId & ProviderType)

```
await _entriesContext.UpsertRange(entry)
   .On(entity => new { entity.ExternalId, entity.ProviderType })
   .RunAsync();
```

**Comment by artiomchi** [comment]
Ahh.. seems like you're using MySql..

The thing about MySql... there's no way to specify which columns you're doing the upsert on in MySql - it will use the unique index that is set up on the table to identify matches..

All you have to do is create a unique index on your table with your keys. I'm not sure if you're allowed to have other unique indexes on the same table for this to work, but that's just a limitation of MySql syntax

**Comment by AirEssY** [comment]
Ahh snap, yea just doing some reading now that was the vibe I was getting. Oh well time to think of a different approach, thanks for your help

**Comment by AirEssY** [comment]
Ok for future reference, adding an HasAlternateKey via fluent API in DbContext fixed my issue 
`modelBuilder.Entity<Review>().HasAlternateKey(r => new { r.ExternalId, r.ProviderType });`
