### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Internal.ICurrentDbContext'

### ISSUE THREAD

**Issue by formalist** [artiomchi/FlexLabs.Upsert#76]
Hi,
i get the following exception when executing an .Upsert.Run():

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'Microsoft.EntityFrameworkCore.**_Internal_**.ICurrentDbContext' from assembly 'Microsoft.EntityFrameworkCore, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  Source=FlexLabs.EntityFrameworkCore.Upsert
  StackTrace:
   at Microsoft.EntityFrameworkCore.UpsertExtensions.Upsert[TEntity](DbSet`1 dbSet, TEntity entity)

in fact, ICurrentDbContext is located under Microsoft.EntityFrameworkCore.**_Infrastructure_** ...

Using EntityFramework Core 3.1, in a Winforms application targeting .NET Framework 4.8.

Thank you.

UPDATE: the same code works in a Console Application targeting .NET Core 3.1 / EntityFramework Core 3.1

**Comment by artiomchi** [comment]
Yeah, Microsoft caused some internal namespace changes with 3.0, and it was targeting `.netstandard2.1`, so this was a good way to differentiate .net core 2.2/.net framework vs .net core 3 builds.

With .NET Core 3.1, they allowed EF Core 3 to run under .NET framework, by re-targeting it back to .NET Standard 2.0.. This is going to cause some headache and compatibility issues. I'll need to come up with a way to handle that, but this is pretty annoying so far :(

**Comment by artiomchi** [comment]
I must have fixed this already, since I've now got .NET 4.8 as a target in the test project, and it's no longer complaining about it, and is running through the tests just fine.

If that's not the case, please let me know and I can take a look again
