### ISSUE TITLE
Using Association Properties with On()

### ISSUE THREAD

**Issue by Mike-E-angelo** [artiomchi/FlexLabs.Upsert#82]
First off, very nice work with this library!  And the API.  It is very easy to use and the fluent API is most excellent. 👍

I was able to get everything working in a project I am working on, however, I did have a problem because I am seeding data that is an entity that looks like the following:

```
public class Authorization
{
	public Guid Id { get; set; }

	public string Name { get; set; }

	public string Claim { get; set; }

	public virtual ICollection<AuthorizationEntry> Entries { get; set; }
}

public class AuthorizationEntry
{
	public Guid Id { get; set; }

	public virtual Authorization Context { get; set; }

	public string Query { get; set; }

	public User User { get; set; }
}
```

Here is my Upsert magic:

```
var administration = new Authorization { ... };
dbContext.Authorizations.Upsert(administration).On(x => x.Name).Run(); // Works!
dbContext.Set<Model.AuthorizationEntry>()
         .Upsert(new Model.AuthorizationEntry
         {
			 Query = "Administrator", Context = administration
         })
         .On(x => new {x.Query, x.Context.Name}) // Exception thrown due to this.
         .Run();
```

It's the `x.Context.Name` that is giving me the trouble.  Essentially, entries can have the same query under contexts, so I am looking to provide uniqueness via the context name.

Is this possible?

Thank you for any assistance you can provide!

**Comment by artiomchi** [comment]
Hi @Mike-E-wins 

Thanks for the kind words and your support of the library! It means a lot to me

Unfortunately, I haven't added any support of navigation properties to the library. It wouldn't work on insert anyway, as the logic of which queries to run would become quite a bit more complex, and as such it won't work on match properties either.

If you know the value of your `ContextId` (or whichever key `Context` uses), you should really match on that. If you don't know it (or it might not even exist), you would have to upsert the context first to make sure it exists, get the context Id, and then run this upsert.

Without knowing more of your code, this is the best I could suggest. Let me know what you think (and I'll try not delay as much before I answer, sorry for that)

**Comment by Mike-E-wins** [comment]
Ah no worries @artiomchi ... I ended up doing it old-skool fashion, basically checking to see if any entities have been added (first time) and if not, adding them. 😁  In my case, I need this for initializing a domain rather than updating it.
