### ISSUE TITLE
ReplaceUpsertCommandRunner extension is not working

### ISSUE THREAD

**Issue by xamele0n** [artiomchi/FlexLabs.Upsert#85]
ReplaceUpsertCommandRunner uses  builder.ReplaceService<IUpsertCommandRunner, TRunner>(); to add implementation of custom interface, but EF Core does not allow to do this 
in ServiceProviderCache.cs
```
var services = new ServiceCollection();
var hasProvider = ApplyServices(options, services);
var replacedServices = coreOptionsExtension?.ReplacedServices;
if (replacedServices != null)
{
	// For replaced services we use the service collection to obtain the lifetime of
	// the service to replace. The replaced services are added to a new collection, after
	// which provider and core services are applied. This ensures that any patching happens
	// to the replaced service.
	var updatedServices = new ServiceCollection();
	foreach (var descriptor in services)
	{
		if (replacedServices.TryGetValue(descriptor.ServiceType, out var replacementType))
		{
			((IList<ServiceDescriptor>)updatedServices).Add(
				new ServiceDescriptor(descriptor.ServiceType, replacementType, descriptor.Lifetime));
		}
	}

	ApplyServices(options, updatedServices);
	services = updatedServices;
}
```
this method used to replace core services and does not allow to add custom service

**Comment by artiomchi** [comment]
Hi @xamele0n 

This is interesting. Could you elaborate on this please? What are you trying to do, what do you expect to happen, and what actually happens? (I really need an issue template for this repo 😄)

Are you making a driver for a different DB, or updating one of the existing ones?

**Comment by xamele0n** [comment]
I tried to change generating sql text for MsSQL provider (remove HOLDLOCK hint). I take exisitng SqlServerUpsertCommandRunner and made own one.
```
new ServiceCollection().AddDbContext<DbContext>(
    d =>
    {                   
        d.UseSqlServer(
            t.options.ConnectionString,
            b => { }).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking).EnableDetailedErrors();
        d.ReplaceUpsertCommandRunner<CustomSqlServerUpsertCommandRunner>();                   
    }).BuildServiceProvider()
```
I expect that CustomSqlServerUpsertCommandRunner was used for generating sql text in Upsert command, but instead of it the default (SqlServerUpsertCommandRunner) implementation used.

I also tried to call ReplaceUpsertCommandRunner extension on same IServiceCollection and behaviour the same (i saw comment on this method, but really don`t understand how to use it in the right way)

I found workaround and use:
```
new ServiceCollection().AddDbContext<DbContext>(
                d =>
                {
                    ((IDbContextOptionsBuilderInfrastructure) d).AddOrUpdateExtension(new UpsertOptionsExtension());
                   ...
                }).BuildServiceProvider();

public class UpsertOptionsExtension : IDbContextOptionsExtension
    {
        public UpsertOptionsExtension()
        {
            this.Info = new ExtensionInfo(this);
        }

        public void ApplyServices(IServiceCollection services)
        {
            services.AddScoped<IUpsertCommandRunner, CustomSqlServerUpsertCommandRunner>();
        }

        public void Validate(IDbContextOptions options)
        {
        }

        public DbContextOptionsExtensionInfo Info { get; }       
    }
```

**Comment by artiomchi** [comment]
Hey @xamele0n 

You're absolutely right.. I must have not noticed this somehow, but EF Core uses it's own service provider internally, so at least one of my extension methods didn't actually do anything.

Your example looks pretty great though, so I'm going to use as the basis for the patch to this issue, which will be released in version 4.

Thanks for your support!
