### ISSUE TITLE
Performance benefit of Upsert

### ISSUE THREAD

**Issue by Sandeep321** [artiomchi/FlexLabs.Upsert#86]
I tried to compare the Add/Update in EF core 3.1 to Upsert but I am getting better performance in the traditional way of add/update. Upsert is around 20% slower than the Add/Update.

Can anyone say that Upsert improves performance also, or is it just about combining multiple statements into fewer ones? If it is for better performance, how about doing that?

**Comment by artiomchi** [comment]
Hi Sandeep,

The main benefit of Upsert isn't performance - it's the atomicity of the operation.

Without Upsert, you could check if an item exists, and if it does - you update it, if it doesn't - you insert it. But if you have multiple parallel requests to the same object, you will either end up overwriting some data, or in a lot of cases - get an exception with multiple requests trying to insert the same entity, breaking a unique index.

Upsert solves that by making an atomic request to the database, which is slower, but safer to perform.

Let me know if you have any more questions, and I'll do my best to answer them

**Comment by Sandeep321** [comment]
Answers my doubts clearly, thanks.
