### ISSUE TITLE
no delete support?

### ISSUE THREAD

**Issue by koo9** [artiomchi/FlexLabs.Upsert#89]
any plan to include delete ?

**Comment by artiomchi** [comment]
Hey @koo9 

Thanks for your interest in this library. At the moment there are no plans to add delete support.

In most cases deletes are pretty safe to run as a separate command, as concurrency wouldn't cause any issues there. The insert/update call on the other hand benefits strongly from the ability to run this as an atomic database command.

Also, MS SQL is the only database engine (from the ones supported here) that can run a DELETE as part of the MERGE statement.. So even if we did add delete support, it wouldn't work on any other database engine, which would just make this library more confusing
