### ISSUE TITLE
Handle the new type conversion introduced in EF core 2.1

### ISSUE THREAD

**Issue by Tarig0** [artiomchi/FlexLabs.Upsert#9]
When utilizing the upsert command it does not recognize type conversions added through fluent API.

```c#
modelBuilder.Entity<Counter>().Property(c => c.Discriminator).HasConversion(d => JsonConvert.SerializeObject(d), s => JsonConvert.DeserializeObject<Dictionary<string, string>>(s));
```

**Comment by gangstatracer** [comment]
Any progress on this enhancement? I've made some experimets in my fork and my solution seems to work. It also should fix https://github.com/artiomchi/FlexLabs.Upsert/issues/8 issue. @artiomchi, please tell what you think about my solution: https://github.com/gangstatracer/FlexLabs.Upsert/commit/1d68ceb6e73f31190b3cad852ecaa7273b4aeddc

**Comment by artiomchi** [comment]
@gangstatracer seems interesting, but needs some work.. I can see that you made some.. a lot of.. unnecessary style changes :)

I'd suggest you start from the latest develop (I've updated the AppVeyor config to work on forks by default), and put only the functional changes + the unit tests there, create a PR and we can take a look.

Also, don't update the NuGet packages to the latest version, just go up to 2.1.0, which is the lowest required version for this feature.
