### ISSUE TITLE
Meaning of RunAsync return value

### ISSUE THREAD

**Issue by Danielku15** [artiomchi/FlexLabs.Upsert#94]
Maybe I'm missing something but I cannot find a good explanation what the integer return value of `RunAsync` would mean. Does it give an indication whether a row was updated or inserted? 

Because that's what I'd like to find out. I need to trigger some particular events based on whether the record is new or not.

**Comment by GioviQ** [comment]
It returns the number of rows affected (See ExecuteSqlRawAsync)

**Comment by artiomchi** [comment]
As @GioviQ  said - it will return the number of rows affected by the query.

Ultimately, this will call `ExecuteSqlRaw` in the `DbContext` and return the result from that call.

See the microsoft docs here: [RelationalDatabaseFacadeExtensions.ExecuteSqlRaw()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationaldatabasefacadeextensions.executesqlraw?view=efcore-3.1#Microsoft_EntityFrameworkCore_RelationalDatabaseFacadeExtensions_ExecuteSqlRaw_Microsoft_EntityFrameworkCore_Infrastructure_DatabaseFacade_System_String_System_Object___)
